#!/bin/bash

echo "Welcome to Not Me CLI!"
command=$(echo "What command would you like to run? ")

if [[ $command == "create-not" ]]; then
  echo "You've just created a new not."
fi

command=$(command)
